---
# CLI tools
cli_packages:
  - git
  - vim
  - tmux
  - htop
  - curl
  - wget
  - unzip
  - tar
  - rsync
  - tree
  - gh

# Desktop/GUI apps
desktop_packages:
  - firefox
  - libreoffice
  - virt-manager

# Development tools
dev_packages:
  - ansible
  - ansible-lint
  - ShellCheck

python_packages:
  - python3
  - python3-pip
  - python3-devel

container_packages:
  - podman
  - podman-compose

# Flatpak apps
flatpak_apps:
  # - com.spotify.Client
  # - com.discordapp.Discord
  # - TODO - add deja dup 
  # - TODO - add bitwarden
