#!/bin/bash

# this script creates a new zettel file with a unique time-based identifier
# and title as the filename. the file is then opened in vim for immediate 
# editing and returns to the directory the script was called from when
# done editing

# display the script usage and description
display_usage() {
    echo -e "Usage: zet [zettel-title] \n"
    echo -e "Description: This script is for creating a new zettelkasten slip.
                          The title should be separated with hyphens or
                          underscores, not spaces."
}

# if a title was not passed in for the zettel
if [[ $# -ne 1 ]]; then
    display_usage
    exit 1
fi

# create the new zettel file
zettel_file=$HOME/repos/zettelkasten/`isosec`_"$1".md
cd $HOME/repos/zettelkasten/
touch "$zettel_file"

# append title section
echo -e "$1\n---" >> "$zettel_file"

# append tags section
echo -e "\n\n---\nTags:\n\n---" >> "$zettel_file"

# append references area
echo -e "\nReferences:\n\n---" >> "$zettel_file"

# Vim into the new zettelkasten file
vim "$zettel_file"

# when done editing file, cd - to return to where you were
# cd -
